#=============================================================================
# Copyright (C) 2013 Daniel Pfeifer <daniel@pfeifer-mail.de>
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#=============================================================================

language: cpp
compiler: gcc

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends g++-4.8 re2c libboost1.53-dev valgrind
  - sudo update-alternatives --quiet --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.6
  - sudo update-alternatives --quiet --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.8
  - sudo update-alternatives --quiet --set gcc /usr/bin/gcc-4.8

script:
  - mkdir _build
  - cd _build
  - cmake -DBUILD_COVERAGE=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build . --target all
  - ctest --output-on-failure .

after_success:
  - if [ $BUILD_TYPE = "Debug" ]; then ./coveralls; fi
